export { default as Layout } from './Layout'
export { default as Home } from './Home'
export { default as Housing } from './Housing'
export { default as About } from './About'
export { default as Error } from './Error'